### ISSUE TITLE
Installing RangeShiftR on Mac

### ISSUE THREAD

**Issue by arcticwarbler** [RangeShifter/RangeShiftR-package#1]
Hello!  I am an MSc student at the University of Aberdeen, and we are using RangeShiftR in our population ecology course.  I am trying to install on my computer.  I have a Mac with High Sierra and am using R version 4.0.2

I have followed the instructions on the website, but when I try 
Rcpp::evalCpp("2+2")

I get this error code:
Error in sourceCpp(code = code, env = env, rebuild = rebuild, cacheDir = cacheDir,  : 
  Error 1 occurred building shared library.

I am not at all familiar with using the Terminal or working with C++ code or anything outside of the RStudio environment.

Thank you so much for your advice and assistance.
Warmly,
Juliann

**Comment by scfpalmer** [comment]
Hi Juliann

Sorry to hear you had this problem, and apologies for the delay in responding to the issue. There appears to be a glitch in our receiving notifications of issues from github. This repo is very new, and we are looking into it.

I understand that you have communicated with my colleagues by email, and they are trying to find a solution to the problem. Hopefully that will not take long, but there's any further problem, please let us know.

Steve

**Comment by annekathleenmalchow** [comment]
Hi,

this problem is actually not related to the RangeshiftR package, but to the setup of the C++ compiler toolchain for R.

After some correspondence via E-Mail, we found the mistake to be an improperly specified R 'Makevars' file. Following the instructions on [this website](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/) it should be deleted but in this case it wasn't due to restricted permissions.
After successfully deleting the 'Makevars' file the toolchain was functional and the package installed successfully.

Anne

**Comment by arcticwarbler** [comment]
Thank you so much to everyone for your help in solving this, and excited to explore RangeShiftR!
